# Generated by Django 4.2 on 2023-04-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(db_index=True, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=100, verbose_name='书籍名称')),
                ('author', models.CharField(max_length=100, verbose_name='书籍作者')),
                ('publisher', models.CharField(default='未定', max_length=100, verbose_name='出版社')),
                ('price', models.CharField(default='无', max_length=100, verbose_name='书籍标价')),
                ('img_url', models.CharField(default='https://via.placeholder.com/150', max_length=100, verbose_name='书籍图片')),
                ('description', models.CharField(default='无', max_length=100, verbose_name='书籍详情')),
                ('pub_date_2', models.DateField(blank=True, default='', null=True, verbose_name='发行时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book_data',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '喜欢的图书',
                'verbose_name_plural': '喜欢的图书',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.bookdata', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '书籍评论',
                'verbose_name_plural': '书籍评论',
                'db_table': 'review',
            },
        ),
    ]
