# Generated by Django 4.2 on 2023-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='description',
            field=models.TextField(default='无', verbose_name='书籍详情'),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='publisher',
            field=models.CharField(default='无', max_length=100, verbose_name='出版社'),
        ),
    ]
